In [ ]:

import pandas as pd

df = pd.read_csv('../01_raw_data/claims/provider_utilization_data.csv')

df.head()

In [2]:

import pandas as pd

df = pd.read_csv('01_raw_data/claims/provider_utilization_data.csv')

df.head()
``

SyntaxError: invalid syntax (885110690.py, line 6)

In [3]:

import os
os.getcwd()

'C:\\Healthcare_Reporting_Portfolio'

In [4]:

df = pd.read_csv('01_raw_data/claims/provider_utilization_data.csv')
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '01_raw_data/claims/provider_utilization_data.csv'

In [5]:

df = pd.read_csv('01_raw_data/claims/provider_utilization_data.csv')
df.head()
``

SyntaxError: invalid syntax (2867567147.py, line 3)

In [7]:

import pandas as pd

df = pd.read_csv('01_raw_data/claims/provider.csv')

df.head()

C:\Users\Latonya\AppData\Local\Temp\ipykernel_113224\1421739311.py:3: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('01_raw_data/claims/provider.csv')

,Rndrng_NPI,Rndrng_Prvdr_Last_Org_Name,Rndrng_Prvdr_First_Name,Rndrng_Prvdr_MI,Rndrng_Prvdr_Crdntls,Rndrng_Prvdr_Ent_Cd,Rndrng_Prvdr_St1,Rndrng_Prvdr_St2,Rndrng_Prvdr_City,Rndrng_Prvdr_State_Abrvtn,...,Bene_CC_PH_Diabetes_V2_Pct,Bene_CC_PH_HF_NonIHD_V2_Pct,Bene_CC_PH_Hyperlipidemia_V2_Pct,Bene_CC_PH_Hypertension_V2_Pct,Bene_CC_PH_IschemicHeart_V2_Pct,Bene_CC_PH_Osteoporosis_V2_Pct,Bene_CC_PH_Parkinson_V2_Pct,Bene_CC_PH_Arthritis_V2_Pct,Bene_CC_PH_Stroke_TIA_V2_Pct,Bene_Avg_Risk_Scre
0,1003000126,Enkeshafi,Ardalan,NaN,M.D.,I,6410 Rockledge Dr Ste 304,NaN,Bethesda,MD,...,45.0,53.0,75.0,75.0,51.0,19.0,4.0,62.0,26.0,2.7545
1,1003000134,Cibull,Thomas,L,M.D.,I,2650 Ridge Ave,Evanston Hospital,Evanston,IL,...,22.0,13.0,75.0,63.0,22.0,19.0,2.0,44.0,6.0,1.1423
2,1003000142,Khalil,Rashid,NaN,M.D.,I,4126 N Holland Sylvania Rd,Suite 220,Toledo,OH,...,44.0,24.0,74.0,75.0,30.0,10.0,NaN,75.0,9.0,1.6448
3,1003000423,Velotta,Jennifer,A,M.D.,I,11100 Euclid Ave,NaN,Cleveland,OH,...,22.0,NaN,75.0,59.0,19.0,22.0,NaN,57.0,NaN,0.7370
4,1003000480,Rothchild,Kevin,B,MD,I,12605 E 16th Ave,NaN,Aurora,CO,...,33.0,16.0,69.0,74.0,27.0,15.0,NaN,63.0,NaN,1.7264

In [8]:

df.shape
``

SyntaxError: invalid syntax (3614908489.py, line 2)

In [9]:
df.shape
``

SyntaxError: invalid syntax (3212102593.py, line 2)

In [10]:
df.shape

(1259343, 81)

In [11]:
df.columns

Index(['Rndrng_NPI', 'Rndrng_Prvdr_Last_Org_Name', 'Rndrng_Prvdr_First_Name',
       'Rndrng_Prvdr_MI', 'Rndrng_Prvdr_Crdntls', 'Rndrng_Prvdr_Ent_Cd',
       'Rndrng_Prvdr_St1', 'Rndrng_Prvdr_St2', 'Rndrng_Prvdr_City',
       'Rndrng_Prvdr_State_Abrvtn', 'Rndrng_Prvdr_State_FIPS',
       'Rndrng_Prvdr_Zip5', 'Rndrng_Prvdr_RUCA', 'Rndrng_Prvdr_RUCA_Desc',
       'Rndrng_Prvdr_Cntry', 'Rndrng_Prvdr_Type',
       'Rndrng_Prvdr_Mdcr_Prtcptg_Ind', 'Tot_HCPCS_Cds', 'Tot_Benes',
       'Tot_Srvcs', 'Tot_Sbmtd_Chrg', 'Tot_Mdcr_Alowd_Amt',
       'Tot_Mdcr_Pymt_Amt', 'Tot_Mdcr_Stdzd_Amt', 'Drug_Sprsn_Ind',
       'Drug_Tot_HCPCS_Cds', 'Drug_Tot_Benes', 'Drug_Tot_Srvcs',
       'Drug_Sbmtd_Chrg', 'Drug_Mdcr_Alowd_Amt', 'Drug_Mdcr_Pymt_Amt',
       'Drug_Mdcr_Stdzd_Amt', 'Med_Sprsn_Ind', 'Med_Tot_HCPCS_Cds',
       'Med_Tot_Benes', 'Med_Tot_Srvcs', 'Med_Sbmtd_Chrg',
       'Med_Mdcr_Alowd_Amt', 'Med_Mdcr_Pymt_Amt', 'Med_Mdcr_Stdzd_Amt',
       'Bene_Avg_Age', 'Bene_Age_LT_65_Cnt', 'Bene_Age_65_74_Cnt',
       'Bene_Age_75_84_Cnt', 'Bene_Age_GT_84_Cnt', 'Bene_Feml_Cnt',
       'Bene_Male_Cnt', 'Bene_Race_Wht_Cnt', 'Bene_Race_Black_Cnt',
       'Bene_Race_API_Cnt', 'Bene_Race_Hspnc_Cnt', 'Bene_Race_NatInd_Cnt',
       'Bene_Race_Othr_Cnt', 'Bene_Dual_Cnt', 'Bene_Ndual_Cnt',
       'Bene_CC_BH_ADHD_OthCD_V1_Pct', 'Bene_CC_BH_Alcohol_Drug_V1_Pct',
       'Bene_CC_BH_Tobacco_V1_Pct', 'Bene_CC_BH_Alz_NonAlzdem_V2_Pct',
       'Bene_CC_BH_Anxiety_V1_Pct', 'Bene_CC_BH_Bipolar_V1_Pct',
       'Bene_CC_BH_Mood_V2_Pct', 'Bene_CC_BH_Depress_V1_Pct',
       'Bene_CC_BH_PD_V1_Pct', 'Bene_CC_BH_PTSD_V1_Pct',
       'Bene_CC_BH_Schizo_OthPsy_V1_Pct', 'Bene_CC_PH_Asthma_V2_Pct',
       'Bene_CC_PH_Afib_V2_Pct', 'Bene_CC_PH_Cancer6_V2_Pct',
       'Bene_CC_PH_CKD_V2_Pct', 'Bene_CC_PH_COPD_V2_Pct',
       'Bene_CC_PH_Diabetes_V2_Pct', 'Bene_CC_PH_HF_NonIHD_V2_Pct',
       'Bene_CC_PH_Hyperlipidemia_V2_Pct', 'Bene_CC_PH_Hypertension_V2_Pct',
       'Bene_CC_PH_IschemicHeart_V2_Pct', 'Bene_CC_PH_Osteoporosis_V2_Pct',
       'Bene_CC_PH_Parkinson_V2_Pct', 'Bene_CC_PH_Arthritis_V2_Pct',
       'Bene_CC_PH_Stroke_TIA_V2_Pct', 'Bene_Avg_Risk_Scre'],
      dtype='object')

In [12]:
df.groupby('npi')['line_srvc_cnt'].sum().sort_values(ascending=False).head(10)

KeyError: 'npi'

In [13]:
df.groupby('Rndrng_NPI')['line_srvc_cnt'].sum().sort_values(ascending=False).head(10)

KeyError: 'Column not found: line_srvc_cnt'

In [14]:
df.groupby('Rndrng_NPI')['Tot_Srvcs'].sum().sort_values(ascending=False).head(10)

Rndrng_NPI
1417915653    21692200.0
1538144910    16020565.0
1013998921    14415062.0
1063477073    13831717.0
1063497451    12292335.0
1932145778     9239764.0
1891731626     8831691.0
1366479099     7632032.0
1043382302     7171071.0
1871881573     6597499.0
Name: Tot_Srvcs, dtype: float64

In [15]:
df.columns.tolist()

['Rndrng_NPI',
 'Rndrng_Prvdr_Last_Org_Name',
 'Rndrng_Prvdr_First_Name',
 'Rndrng_Prvdr_MI',
 'Rndrng_Prvdr_Crdntls',
 'Rndrng_Prvdr_Ent_Cd',
 'Rndrng_Prvdr_St1',
 'Rndrng_Prvdr_St2',
 'Rndrng_Prvdr_City',
 'Rndrng_Prvdr_State_Abrvtn',
 'Rndrng_Prvdr_State_FIPS',
 'Rndrng_Prvdr_Zip5',
 'Rndrng_Prvdr_RUCA',
 'Rndrng_Prvdr_RUCA_Desc',
 'Rndrng_Prvdr_Cntry',
 'Rndrng_Prvdr_Type',
 'Rndrng_Prvdr_Mdcr_Prtcptg_Ind',
 'Tot_HCPCS_Cds',
 'Tot_Benes',
 'Tot_Srvcs',
 'Tot_Sbmtd_Chrg',
 'Tot_Mdcr_Alowd_Amt',
 'Tot_Mdcr_Pymt_Amt',
 'Tot_Mdcr_Stdzd_Amt',
 'Drug_Sprsn_Ind',
 'Drug_Tot_HCPCS_Cds',
 'Drug_Tot_Benes',
 'Drug_Tot_Srvcs',
 'Drug_Sbmtd_Chrg',
 'Drug_Mdcr_Alowd_Amt',
 'Drug_Mdcr_Pymt_Amt',
 'Drug_Mdcr_Stdzd_Amt',
 'Med_Sprsn_Ind',
 'Med_Tot_HCPCS_Cds',
 'Med_Tot_Benes',
 'Med_Tot_Srvcs',
 'Med_Sbmtd_Chrg',
 'Med_Mdcr_Alowd_Amt',
 'Med_Mdcr_Pymt_Amt',
 'Med_Mdcr_Stdzd_Amt',
 'Bene_Avg_Age',
 'Bene_Age_LT_65_Cnt',
 'Bene_Age_65_74_Cnt',
 'Bene_Age_75_84_Cnt',
 'Bene_Age_GT_84_Cnt',
 'Bene_Feml_Cnt',
 'Bene_Male_Cnt',
 'Bene_Race_Wht_Cnt',
 'Bene_Race_Black_Cnt',
 'Bene_Race_API_Cnt',
 'Bene_Race_Hspnc_Cnt',
 'Bene_Race_NatInd_Cnt',
 'Bene_Race_Othr_Cnt',
 'Bene_Dual_Cnt',
 'Bene_Ndual_Cnt',
 'Bene_CC_BH_ADHD_OthCD_V1_Pct',
 'Bene_CC_BH_Alcohol_Drug_V1_Pct',
 'Bene_CC_BH_Tobacco_V1_Pct',
 'Bene_CC_BH_Alz_NonAlzdem_V2_Pct',
 'Bene_CC_BH_Anxiety_V1_Pct',
 'Bene_CC_BH_Bipolar_V1_Pct',
 'Bene_CC_BH_Mood_V2_Pct',
 'Bene_CC_BH_Depress_V1_Pct',
 'Bene_CC_BH_PD_V1_Pct',
 'Bene_CC_BH_PTSD_V1_Pct',
 'Bene_CC_BH_Schizo_OthPsy_V1_Pct',
 'Bene_CC_PH_Asthma_V2_Pct',
 'Bene_CC_PH_Afib_V2_Pct',
 'Bene_CC_PH_Cancer6_V2_Pct',
 'Bene_CC_PH_CKD_V2_Pct',
 'Bene_CC_PH_COPD_V2_Pct',
 'Bene_CC_PH_Diabetes_V2_Pct',
 'Bene_CC_PH_HF_NonIHD_V2_Pct',
 'Bene_CC_PH_Hyperlipidemia_V2_Pct',
 'Bene_CC_PH_Hypertension_V2_Pct',
 'Bene_CC_PH_IschemicHeart_V2_Pct',
 'Bene_CC_PH_Osteoporosis_V2_Pct',
 'Bene_CC_PH_Parkinson_V2_Pct',
 'Bene_CC_PH_Arthritis_V2_Pct',
 'Bene_CC_PH_Stroke_TIA_V2_Pct',
 'Bene_Avg_Risk_Scre']

In [16]:
[col for col in df.columns if 'Srv' in col or 'Serv' in col]

['Tot_Srvcs', 'Drug_Tot_Srvcs', 'Med_Tot_Srvcs']

In [17]:
df.groupby('Rndrng_NPI')['Tot_Srvcs'].sum().sort_values(ascending=False).head(10)

Rndrng_NPI
1417915653    21692200.0
1538144910    16020565.0
1013998921    14415062.0
1063477073    13831717.0
1063497451    12292335.0
1932145778     9239764.0
1891731626     8831691.0
1366479099     7632032.0
1043382302     7171071.0
1871881573     6597499.0
Name: Tot_Srvcs, dtype: float64

In [18]:

report = df.groupby('Rndrng_NPI')['Tot_Srvcs'].sum().reset_index()

report = report.sort_values(by='Tot_Srvcs', ascending=False).head(10)

report.to_csv('04_outputs/top_providers.csv', index=False)

report

         Rndrng_NPI   Tot_Srvcs
526597   1417915653  21692200.0
669817   1538144910  16020565.0
25288    1013998921  14415062.0
79465    1063477073  13831717.0
80148    1063497451  12292335.0
1172549  1932145778   9239764.0
1127959  1891731626   8831691.0
458417   1366479099   7632032.0
54930    1043382302   7171071.0
1106436  1871881573   6597499.0

In [19]:

report = df.groupby('Rndrng_NPI')['Tot_Srvcs'].sum().reset_index()

report = report.sort_values(by='Tot_Srvcs', ascending=False).head(10)

report

         Rndrng_NPI   Tot_Srvcs
526597   1417915653  21692200.0
669817   1538144910  16020565.0
25288    1013998921  14415062.0
79465    1063477073  13831717.0
80148    1063497451  12292335.0
1172549  1932145778   9239764.0
1127959  1891731626   8831691.0
458417   1366479099   7632032.0
54930    1043382302   7171071.0
1106436  1871881573   6597499.0

In [20]:

report = df.groupby('Rndrng_NPI')['Tot_Srvcs'].sum().reset_index()

report = report.sort_values(by='Tot_Srvcs', ascending=False).head(10)

report

         Rndrng_NPI   Tot_Srvcs
526597   1417915653  21692200.0
669817   1538144910  16020565.0
25288    1013998921  14415062.0
79465    1063477073  13831717.0
80148    1063497451  12292335.0
1172549  1932145778   9239764.0
1127959  1891731626   8831691.0
458417   1366479099   7632032.0
54930    1043382302   7171071.0
1106436  1871881573   6597499.0